### ISSUE TITLE
Integration failed to initialize - Uncaught thread exception

### ISSUE THREAD

**Issue by sisaenkov** [Misiu/argon40#15]
## Version of the custom_component

0.0.2

## Describe the bug
Integration doesn't start.
I have enabled i2c with configuration below:
config.txt:
```
dtparam=i2c1=on
dtparam=i2c_arm=on
```
rpi-i2c.conf:
```
i2c-bcm2708
i2c-bcm2835
i2c-dev
```

Raspberry Pi 4
HassOS 4.17
Home Assistant 0.118.2

## Debug log

```text

2020-11-21 18:21:20 INFO (MainThread) [homeassistant.setup] Setting up argon40
2020-11-21 18:21:20 INFO (MainThread) [custom_components.argon40] 
-------------------------------------------------------------------
Argon40
Version: 0.0.2
This is a custom integration!
If you have any issues with this you need to open an issue here:
https://github.com/Misiu/argon40/issues
-------------------------------------------------------------------

2020-11-21 18:21:20 INFO (MainThread) [homeassistant.setup] Setup of domain argon40 took 0.0 seconds
2020-11-21 18:21:20 ERROR (MainThread) [homeassistant.setup] Setup failed for argon40: Integration failed to initialize.
2020-11-21 18:21:20 ERROR (Thread-2) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/logging/handlers.py", line 1487, in _monitor
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/handlers.py", line 1468, in handle
    handler.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 195, in emit
    entry = LogEntry(record, stack, _figure_out_source(record, stack, self.hass))
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 100, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not NoneType


2020-11-21 18:21:20 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=persistent_notification, service=create, service_data=title=Invalid config, message=The following integrations and platforms could not
 be set up:

 - argon40

Please check your config and [logs](/config/logs)., notification_id=invalid_config>


2020-11-21 18:21:22 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=persistent_notification.invalid_config, old_state=None, new_state=<state persistent_notification.invalid_config=notifying; title=I
nvalid config, message=The following integrations and platforms could not be set up:

 - argon40

Please check your config and [logs](/config/logs). @ 2020-11-21T18:21:22.645930+03:00>>

```

**Comment by sisaenkov** [comment]
Still actual
